export const AuditActions = {
  CATEGORY_CREATED: "CATEGORY_CREATED",

  CATEGORY_UPDATED: "CATEGORY_UPDATED",

  CATEGORY_DELETED: "CATEGORY_DELETED",

  PRODUCT_CREATED: "PRODUCT_CREATED",

  PRODUCT_UPDATED: "PRODUCT_UPDATED",

  OPTION_GROUP_CREATED: "OPTION_GROUP_CREATED",

  OPTION_GROUP_UPDATED: "OPTION_GROUP_UPDATED",

  OPTION_CREATED: "OPTION_CREATED",

  OPTION_UPDATED: "OPTION_UPDATED",

  OPTION_DELETED: "OPTION_DELETED",

  PRODUCT_OPTION_GROUP_ATTACHED: "PRODUCT_OPTION_GROUP_ATTACHED",

  PRODUCT_OPTION_GROUP_DETACHED: "PRODUCT_OPTION_GROUP_DETACHED",

  ORDER_CREATED: "ORDER_CREATED",

  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",

  WHATSAPP_CONVERSATION_RESUMED: "WHATSAPP_CONVERSATION_RESUMED",

  WHATSAPP_MESSAGE_SENT: "WHATSAPP_MESSAGE_SENT",
} as const;

export const AuditEntityTypes = {
  CATEGORY: "Category",
  PRODUCT: "Product",
  OPTION_GROUP: "OptionGroup",
  OPTION: "Option",
  PRODUCT_OPTION_GROUP: "ProductOptionGroup",
  TENANT: "Tenant",
  USER: "User",
  ORDER: "Order",
  WHATSAPP_CONVERSATION: "WhatsAppConversation",
} as const;
